import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import { EdgeStoreProvider } from '../lib/edgestore';
import ModalProvider from '@/components/providers/modal-provider'
import { ThemeProvider } from '@/components/providers/theme-provider';
import { QueryProvider } from '@/components/providers/query-provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  
      <html lang="en">
      <body className={inter.className}>
      <EdgeStoreProvider>
        <ModalProvider />
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            
          >
            <QueryProvider>

           
        {children}
        </QueryProvider>
        </ThemeProvider>
        </EdgeStoreProvider>
      <Toaster richColors position='top-right'/>
      </body>
    </html>
  
    
  )
}
